<Project>
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Authors>Nazar Lukianov</Authors>
    <Company>FinancialTracker</Company>
    <RepositoryUrl>https://github.com/AlesonDev/Financial.Common</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
</Project>