<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Financial.Tracker.Messaging.Abstractions" Version="1.0.0" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.3" />
    <PackageVersion Include="RabbitMQ.Client" Version="7.2.0" />
  </ItemGroup>
</Project>