<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup>
    <Version>1.0.0</Version>
    <Nullable>enable</Nullable>
    <Description>RabbitMQ implementation of FinancialTracker messaging abstractions.</Description>
  </PropertyGroup>
</Project>