<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Financial.Tracker.Messaging.RabbitMq</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Financial.Tracker.Messaging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="RabbitMQ.Client" />
  </ItemGroup>

</Project>
